/*-
 * ============LICENSE_START=======================================================
 * org.openecomp.aai
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.26 at 06:45:14 PM EDT 
//


package org.openecomp.aai.domain.search;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inventory-item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inventory-item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inventory-item-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inventory-item-link" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inventory-item-data" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="property-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="property-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tagged-inventory-item-list" type="{http://org.openecomp.aai.inventory/v8}tagged-inventory-item-list" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inventory-item", propOrder = {
    "inventoryItemType",
    "inventoryItemLink",
    "inventoryItemData",
    "taggedInventoryItemList"
})
public class InventoryItem {

    @XmlElement(name = "inventory-item-type")
    protected String inventoryItemType;
    @XmlElement(name = "inventory-item-link")
    protected String inventoryItemLink;
    @XmlElement(name = "inventory-item-data")
    protected List<InventoryItemData> inventoryItemData;
    @XmlElement(name = "tagged-inventory-item-list")
    protected List<TaggedInventoryItemList> taggedInventoryItemList;

    /**
     * Gets the value of the inventoryItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryItemType() {
        return inventoryItemType;
    }

    /**
     * Sets the value of the inventoryItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryItemType(String value) {
        this.inventoryItemType = value;
    }

    /**
     * Gets the value of the inventoryItemLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryItemLink() {
        return inventoryItemLink;
    }

    /**
     * Sets the value of the inventoryItemLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryItemLink(String value) {
        this.inventoryItemLink = value;
    }

    /**
     * Gets the value of the inventoryItemData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inventoryItemData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInventoryItemData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InventoryItemData }
     *
     * @return the inventory item data
     */
    public List<InventoryItemData> getInventoryItemData() {
        if (inventoryItemData == null) {
            inventoryItemData = new ArrayList<InventoryItemData>();
        }
        return this.inventoryItemData;
    }

    /**
     * Gets the value of the taggedInventoryItemList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taggedInventoryItemList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaggedInventoryItemList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaggedInventoryItemList }
     *
     * @return the tagged inventory item list
     */
    public List<TaggedInventoryItemList> getTaggedInventoryItemList() {
        if (taggedInventoryItemList == null) {
            taggedInventoryItemList = new ArrayList<TaggedInventoryItemList>();
        }
        return this.taggedInventoryItemList;
    }

}
